// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_CO9-g9EsG2-1heGhXe6hcoCK1xTu1aE',
    appId: '1:387655217072:web:ed44b4db39462804633075',
    messagingSenderId: '387655217072',
    projectId: 'notes-485a4',
    authDomain: 'notes-485a4.firebaseapp.com',
    storageBucket: 'notes-485a4.firebasestorage.app',
    measurementId: 'G-MF74ZFF1J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiAUaBrbcqllB8SZmxREO3-yZPqCGBxM',
    appId: '1:387655217072:android:fafc05eddb1249f8633075',
    messagingSenderId: '387655217072',
    projectId: 'notes-485a4',
    storageBucket: 'notes-485a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD01EobzCxVN4tMUmkYDtqp2MzGeuqvK0',
    appId: '1:387655217072:ios:63982aae021fdd89633075',
    messagingSenderId: '387655217072',
    projectId: 'notes-485a4',
    storageBucket: 'notes-485a4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAct',
  );
}
